-- Sửa cột mã job (code) đang NULL → tạo lại dạng tự tăng (Identity).
-- ⚠ Tắt app (pnpm dev) trước khi chạy để tránh kẹt khóa/timeout.

-- Tăng giới hạn thời gian cho phiên này (phòng khi chờ khóa).
SET statement_timeout = '5min';

-- Bỏ cột cũ (đang rỗng/không có default) rồi tạo lại đúng.
ALTER TABLE "jobs" DROP COLUMN IF EXISTS "code";

-- Postgres tự điền mã cho job đã tồn tại và tự cấp mã cho job mới.
ALTER TABLE "jobs"
  ADD COLUMN "code" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE;
